@startuml
scale 2
:Felhasználó: as user

(Új poligon hozzáadása) as new_group
(poligon törlése) as delete_group
(Csúcs hozzáadása) as add_vertex
(poligon eltolása) as offset_group
(Csúcs törlése) as delete_vertex


user -- new_group
user - delete_group
add_vertex -- user
offset_group -- user
delete_vertex - user

@enduml
